MEMORY
{
  IORAM (wa): ORIGIN = 0x00800000, LENGTH = 8M
  RAM (wxa) : ORIGIN = 0x01000000, LENGTH = 128M
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);